### ISSUE TITLE
bad using of audiowrite.m

### ISSUE THREAD

**Issue by jean-remyGloaguen** [mathieulagrange/expLanes#11]
In the denoiseAudio demo, in deauInit.m, line 29 and 38, the use of audiowrite fonction is not correct. The first input argument should be the name of the file where we want to put the data. Here the variable fileName is the last input variable.
Suggestion for the two lines : audiowrite(sourceFileName,store.source,config.samplingFrequency), it works !

**Comment by mathieulagrange** [comment]
indeed, fixed.
