### ISSUE TITLE
Undefined function or variable

### ISSUE THREAD

**Issue by gregoirelafay** [mathieulagrange/expLanes#18]
At the end of step

Undefined function or variable 'savejson'.

Error in expExpose (line 695)
    savejson('', json, [htmlPath  'test.json']);

Error in expRun>exposeObservations (line 313)
        config = expExpose(config, config.expose);

Error in expRun (line 228)
        config = exposeObservations(config);

Error in ass_hist_features (line 15)
 config = expRun(p, experimentName, shortExperimentName, varargin);

Error in ashife2sceneFeatures (line 45)

**Comment by mathieulagrange** [comment]
forgot to add stuff, sorry :/
