### ISSUE TITLE
infinite ? loop

### ISSUE THREAD

**Issue by gregoirelafay** [mathieulagrange/expLanes#19]
when running report, and terminate computation after one minute

Operation terminated by user during sortrows (line 71)

In uniqueRuniqueR2012a (line 278)
        [sortA,indSortA] = sortrows(a);

In unique (line 146)
        [varargout{1:nlhs}] = uniqueR2012a(varargin{1},logical(flaginds(1:5)));

In expSettingSet (line 17)
[newmat, index] = unique(vSet','rows','first');  % Finds indices of unique rows

In expStepSetting (line 3)
vSet = expSettingSet(vSpec, mask, currentStep);

In expRun (line 155)
    [config.stepSettings{rem(k)}] = expStepSetting(config.factors, config.mask, rem(k));

In ass_hist_features (line 15)
 config = expRun(p, experimentName, shortExperimentName, varargin);

In ashifeReport (line 9)
if nargin==0, ass_hist_features('report', 'r'); return; end

**Comment by mathieulagrange** [comment]
If the sort is too long, most probably the numnber of settings is very very large. Please try to reduce the number of settings and see if things stay the same

**Comment by gregoirelafay** [comment]
In expRun l12

if isempty(config.factors)
   config.mask = {{}};
elseif ~expCheckMask(config.factors, config.mask)
   mask = cell(1, length(config.factors.names));
   [mask{:}] = deal(-1);
   config.mask = {mask};
end

// When report is run, config.mask = {{}}.
// To avoid that, change to the following:

if isempty(config.factors)
   config.mask = {{}};
elseif ~expCheckMask(config.factors, config.mask) || strcmp(commands{1},'report')
   mask = cell(1, length(config.factors.names));
   [mask{:}] = deal(-1);
   config.mask = {mask};
end

**Comment by mathieulagrange** [comment]
fixed, thank you
