### ISSUE TITLE
expExpose: name '+'

### ISSUE THREAD

**Issue by gregoirelafay** [mathieulagrange/expLanes#21]
When using name = '+' in expExpose (default option):

Nom de fichier trop long
Error using textread (line 165)
File not found.

Error in LatexCreator/writeLatexFile (line 336)
        TEX=textread(Data.FullTexFn,'%s','delimiter','\n');

Error in LatexCreator/addTable (line 844)
        writeLatexFile();

Error in expSaveTable (line 5)
latex.addTable(table.table, 'caption', table.caption, 'multipage', table.multipage, 'landscape', table.landscape, 'label', table.label,
'fontSize', table.fontSize, 'nbFactors', table.nbFactors)

Error in expExpose (line 714)
        expSaveTable([config.reportPath 'tables/' name '.tex'], config.displayData.table(end));

Error in asclfeReport (line 47)
    config = expExpose(config,'t','fontSize','scriptsize','step',7, 'mask', {...

Error in expRun (line 241)
        config = feval([config.shortExperimentName 'Report'], config);

Error in ass_clustering_features (line 15)
 config = expRun(p, experimentName, shortExperimentName, varargin);

Error in asclfeReport (line 9)
if nargin==0, ass_clustering_features('report', 'rcv'); return; end

**Comment by mathieulagrange** [comment]
fixed with short namings

**Comment by mathieulagrange** [comment]
you can also specify a name as string
