### ISSUE TITLE
Merging Factor

### ISSUE THREAD

**Issue by gregoirelafay** [mathieulagrange/expLanes#7]
During the merging step: 

Incorrect number of right hand side elements in dot name assignment.  Missing [] around left hand side is a likely cause.

Error in expOperate>expProcessOneSub (line 183)
            loadedData.obs = obs;

Error in expOperate>expProcessOne (line 120)
        config = expProcessOneSub(config);

Error in expOperate (line 100)
                config = expProcessOne(config, l);

Error in expRun (line 225)
    config = expOperate(config);

**Comment by glafay** [comment]
> At

**Comment by mathieulagrange** [comment]
fixed.
